# Generated by Django 5.1.5 on 2025-01-27 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'پیام', 'verbose_name_plural': 'پیام\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='privetchat',
            options={'verbose_name': 'چت خصوصی', 'verbose_name_plural': 'چت\u200cهای خصوصی'},
        ),
    ]
