"""
Django settings for dj project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c@_cso#%fy6y%!b2gy6n_-o+c^**jy)pe-9+1qu1jswpp(2fne'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'channels',
    # 'material',  # کتابخانه اصلی
    # 'material.admin',
    # # 'grappelli',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # apps
    'Chat'
]






JAZZMIN_SETTINGS = {
    # سایر تنظیمات قبلی شما
    "show_language_picker": True,  # نمایش انتخاب زبان
    "translations": True,  # فعال کردن ترجمه
    "language_chooser": True,  # نمایش لیست زبان‌ها
    # سایت و برند
    "site_title": "Library Admin",
    "site_header": "Library Management",
    "site_brand": "Library Admin",
    "site_logo": "books/img/logo.png",  # مسیر لوگوی دلخواه
    "site_logo_classes": "img-circle",
    "site_icon": "books/img/logo.png",  # آیکون مرورگر
    "welcome_sign": "Welcome to the Library Admin Panel",
    "copyright": "© 2025 Library Inc",  # فعال‌سازی انتخاب زبان
    "theme": "green",
    # منوی بالا
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Docs", "url": "https://docs.djangoproject.com/", "new_window": True},
        {"model": "auth.User"},
        {"app": "books"},
    ],

    # منوی کاربر
    "usermenu_links": [
        {"name": "Profile", "url": "/profile", "icon": "fas fa-user-circle"},
        {"name": "Support", "url": "https://support.example.com", "new_window": True, "icon": "fas fa-life-ring"},
    ],

    # منوی جانبی
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
    "custom_links": {
        "books": [
            {
                "name": "Generate Report",
                "url": "generate_report",
                "icon": "fas fa-chart-line",
                "permissions": ["books.view_book"]
            },
            {
                "name": "Send Notifications",
                "url": "send_notifications",
                "icon": "fas fa-envelope",
                "permissions": ["books.view_book"]
            }
        ]
    },

    # آیکون‌های اپلیکیشن‌ها و مدل‌ها
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "books": "fas fa-book",
        "books.author": "fas fa-feather-alt",
        "books.book": "fas fa-book-open",
    },
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",

    # مدل مرتبط
    "related_modal_active": True,

    # تغییرات UI
    "custom_css": "css/custom_admin.css",  # مسیر فایل CSS دلخواه
    "custom_js": "js/custom_admin.js",  # مسیر فایل JS دلخواه
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,

    # تغییر نمایش فرم‌ها
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "vertical_tabs",
        "auth.group": "collapsible"
    },


}





MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'dj.wsgi.application'
ASGI_APPLICATION = 'dj.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en'  # زبان پیش‌فرض فارسی
TIME_ZONE = 'Asia/Tehran'  # تنظیم منطقه زمانی ایران

USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ('fa', _('Persian')),  # زبان فارسی
    ('en', _('English')),  # زبان انگلیسی (در صورت نیاز)
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# settings.py
LOGIN_REDIRECT_URL = '/chat/users/list/'  # مسیر دلخواه شما


# MATERIAL_ADMIN_SITE = {
#     'HEADER': 'My Admin Panel',  # متن بالای صفحه
#     'TITLE': 'Admin Panel',      # عنوان تب مرورگر
#     'FAVICON': 'path/to/favicon.ico',  # آیکون تب مرورگر
#     'MAIN_BG_COLOR': '#2196f3',  # رنگ پس‌زمینه نوار بالایی
#     'MAIN_HOVER_COLOR': '#1e88e5',  # رنگ هاور لینک‌ها
#     'PROFILE_PICTURE': 'path/to/profile.jpg',  # مسیر عکس پروفایل
#     'PROFILE_BG': 'path/to/background.jpg',  # تصویر پس‌زمینه پروفایل
#     'LOGIN_LOGO': 'path/to/logo.png',  # لوگوی صفحه ورود
#     'LOGOUT_BG': 'path/to/logout_bg.jpg',  # تصویر پس‌زمینه صفحه خروج
#     'SHOW_THEMES': True,           # نمایش تغییر تم (True یا False)
#     'TRAY_REVERSE': False,         # ترتیب معکوس برای منو
#     'NAVBAR_FIXED': True,          # فیکس کردن نوار بالایی
# }


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}
